In [0]:
import numpy as np
import math
import scipy as sc
import pandas as pd
np.set_printoptions(suppress=True)
np.set_printoptions(precision=4)
from pprint import pprint
from numpy import array, zeros, diag, diagflat, dot

In [160]:
mat = np.array([[1,2,3,1], [1,2,1,0]])
[a,b] = mat.shape
mat[1,] - 2*mat[0,]

array([-1, -2, -5, -2])

In [0]:
  def step(mat, ele):
    [n,m] = mat.shape
    for i in range(ele+1,n):
      k = mat[i,ele]/mat[ele, ele]
      mat[i,] = mat[i,] - (k*mat[ele,])
    return mat
  
  def GEM(mat):
    [n,m] = mat.shape
    for ele in range(n-1):
      mat = step(mat, ele)
    print(mat,'\n\n')
    print(sc.linalg.solve(mat[0:,:-1],mat[:,-1:]))                                         

In [162]:
mat = np.array([[1,2,1,0],[2,2,3,3],[-1,-3,0,2]], dtype=np.float32)
GEM(mat)


[[ 1.   2.   1.   0. ]
 [ 0.  -2.   1.   3. ]
 [ 0.   0.   0.5  0.5]] 


[[ 1.]
 [-1.]
 [ 1.]]


In [163]:
mat = np.array([[4,3,2,1,1],[3,4,3,2,1],[2,3,4,3,-1],[1,2,3,4,-1]], dtype=np.float32)
mat = GEM(mat)

[[ 4.      3.      2.      1.      1.    ]
 [ 0.      1.75    1.5     1.25    0.25  ]
 [ 0.      0.      1.7143  1.4286 -1.7143]
 [ 0.      0.      0.      1.6667  0.    ]] 


[[ 0.]
 [ 1.]
 [-1.]
 [ 0.]]


In [165]:
mat = np.array([[1,1,-1], [1,2,-2], [-2,1,1]], dtype=np.float32)
print(mat, '\n\n')
inv = sc.linalg.inv(mat)
print(inv, '\n\n')
print(np.matmul(mat,inv))

[[ 1.  1. -1.]
 [ 1.  2. -2.]
 [-2.  1.  1.]] 


[[ 2.  -1.  -0. ]
 [ 1.5 -0.5  0.5]
 [ 2.5 -1.5  0.5]] 


[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [172]:
def jacobi(A,b,N=25,x=None):                                                                                                                                                         
    if x is None:
        x = zeros(len(A[0]))
                                                                                                                                                                   
    D = diag(A)
    R = A - diagflat(D)
                                                                                                                                                                         
    for i in range(N):
        x = (b - dot(R,x)) / D
    return x

A = array([[9,1,1],[2,10,3], [3,4,11]], dtype=np.float32)
b = array([10.0,19.0,0.0], dtype=np.float32)
guess = array([1.0,1.0, 1.0], dtype=np.float32)

sol = jacobi(A,b,N=25,x=guess)

print("A:")
print(A, '\n\n')

print("b:")
print(b, '\n\n')

print("x:")
print(sol)

A:
[[ 9.  1.  1.]
 [ 2. 10.  3.]
 [ 3.  4. 11.]] 


b:
[10. 19.  0.] 


x:
[ 1.  2. -1.]
